### ISSUE TITLE
Package names for prerequisites not complete

### ISSUE THREAD

**Issue by freakyjoe** [hintjens/mkbook#2]
On Ubuntu it should be:
- pygmentize: python-pygments
- rasterizer: libbatik-java and libxmlgraphics-commons-java

**Comment by hintjens** [comment]
Will you send a pull request? I'll make it clear how contributions work in
the README.

**Comment by freakyjoe** [comment]
Sure!

**Comment by freakyjoe** [comment]
PR been merged. Close.
